### PR TITLE
Introduce makefiles for building Nextor

### PR DESCRIPTION
**Pull request by Konamiman**
This pull request introduces makefiles for proper incremental build of Nextor. Makefiles are introduced in the following directories:

- `source/kernel`
- `source/command/msxdos`
- `source/tools`
- `source/tools/C`

Also there's a top-level makefile in `source/` that invokes all others. See the `README` file for some more details.

The old `compile.sh` scripts are removed. The even older `compile.bat` Windows scripts are kept, but will probably be removed in the future.

Worth mentioning [the amazing pull request from Dean Netherton](https://github.com/Konamiman/Nextor/pull/79) where he took an alternative approach and provided way more comprehensive makefiles.

### CODE REVIEW

**Comment by igmar** [comment]
What is the target make ? The GNU one ? BSD ? I have quite some suggestions, but it depends on the target make.

**Comment by Konamiman** [comment]
Hi @igmar, I'm using Linux so I guess it's GNU?

**Comment by igmar** [comment]
On Linux, its Gnu indeed. I'll go over it in the coming days.

**Comment by igmar** [comment]
Ok, I've gone over it, and I've got a couple of proposals, in which I can help.

1) I propose that we go for an inclusive make : Make top-level makes include subdirectory makes. That has as an advantage that Make has a full set of dependencies in scope. Most likely not extremely useful, but it will get rid of a lot of boilerplate code when the project grows.

top-level Makefile just contains global definitions (compilers, global flags, etc), and includes Rules.mk. top-level Rules.mk contains generic transformations (for example %.c -> %.o), and also contains the clean target (for which the targets get filled by downstream Rules.mk files).

2) See if we can make a proper scoped target, where the final object is assembled from all the other objects. Mostly to make it more clean, not because of speed.

On a sidenote, is there a way we can replace M80 with zmac ? This is a lot easier to get running, but I'm not familiar enough with either one to make any judgement on this.

I can get started on 1) and 2) if you want.

**Comment by Konamiman** [comment]
Hi @igmar, sorry for taking too long to answer.

Thanks for your suggestion and offer, but I think I prefer to keep one single makefile per area (kernel, NEXTOR.SYS, tools) for now. It helps me to see "at a glance" all that's in scope for building, and the files are not that big for now (the biggest one is the makefile for the kernel and it's about 500 lines long). I might reconsider this in the future if the project really grows a lot.

**Pull request merged**
